# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  database: library_development
  username: root
  password: maheshwari
  host: localhost
test:
  adapter: mysql2
  database: library_test
  username: root
  password: maheshwari
  host: localhost
production:
  adapter: mysql2
  database: library_production
  username: root
  password: maheshwari
  host: localhost